# Generated by Django 6.0.6 on 2026-06-22 09:53

import assessments.models
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0009_auto_20260621_2246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('private_notebook', models.FileField(storage=assessments.models.PrivateAssessmentFileSystemStorage(), upload_to='private_submissions/', validators=[assessments.models.validate_notebook_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('sha256_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('evaluating', 'Evaluating'), ('graded', 'Graded'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_started_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_finished_at', models.DateTimeField(blank=True, null=True)),
                ('safe_failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('safe_failure_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('passed_tests', models.PositiveIntegerField()),
                ('failed_tests', models.PositiveIntegerField()),
                ('total_tests', models.PositiveIntegerField()),
                ('evaluator_version', models.CharField(max_length=50)),
                ('safe_summary', models.TextField(blank=True)),
                ('safe_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='assessments.assessmentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('hidden_tests', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('display_order', models.IntegerField()),
                ('language', models.CharField(default='python', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version_snapshot', models.PositiveIntegerField()),
                ('candidate_name_snapshot', models.CharField(max_length=255)),
                ('candidate_email_snapshot', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('email_pending', 'Email Pending'), ('invited', 'Invited'), ('started', 'Started'), ('submitted', 'Submitted'), ('queued', 'Queued'), ('evaluating', 'Evaluating'), ('graded', 'Graded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('secure_token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('assessment_deadline', models.DateTimeField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('assigned_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_started_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('safe_failure_message', models.TextField(blank=True, null=True)),
                ('assessment_snapshot', models.JSONField(validators=[assessments.models.validate_assessment_snapshot])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_provider', models.CharField(default='brevo', max_length=50)),
                ('email_status', models.CharField(choices=[('not_queued', 'Not Queued'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('deferred', 'Deferred'), ('soft_bounced', 'Soft Bounced'), ('hard_bounced', 'Hard Bounced'), ('blocked', 'Blocked'), ('complaint', 'Complaint'), ('failed', 'Failed')], default='not_queued', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('email_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('email_failed_at', models.DateTimeField(blank=True, null=True)),
                ('email_last_event_at', models.DateTimeField(blank=True, null=True)),
                ('email_failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('email_failure_message', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_assessments', to='applications.application')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_assessments', to='assessments.assessmenttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='candidate_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='assessments.candidateassessment'),
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_awarded', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passed_tests', models.PositiveIntegerField()),
                ('failed_tests', models.PositiveIntegerField()),
                ('safe_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_results', to='assessments.assessmentquestion')),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='assessments.assessmentresult')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment_result', 'question'), name='unique_qresult_result_question'), models.CheckConstraint(condition=models.Q(('score_awarded__gte', 0)), name='qresult_score_awarded_non_negative'), models.CheckConstraint(condition=models.Q(('maximum_score__gt', 0)), name='qresult_maximum_score_positive'), models.CheckConstraint(condition=models.Q(('score_awarded__lte', models.F('maximum_score'))), name='qresult_score_bound'), models.CheckConstraint(condition=models.Q(('passed_tests__gte', 0)), name='qresult_passed_tests_non_negative'), models.CheckConstraint(condition=models.Q(('failed_tests__gte', 0)), name='qresult_failed_tests_non_negative')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0)), name='result_total_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_score__gt', 0)), name='result_maximum_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='result_percentage_bounds'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('passed_tests__gte', 0)), name='result_passed_tests_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('failed_tests__gte', 0)), name='result_failed_tests_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_tests__gte', 0)), name='result_total_tests_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_tests', django.db.models.expressions.CombinedExpression(models.F('passed_tests'), '+', models.F('failed_tests')))), name='result_tests_count_consistency'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__lte', models.F('maximum_score'))), name='result_score_consistency'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_template_name_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='template_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='template_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('template', 'display_order'), name='unique_question_template_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('marks__gt', 0)), name='question_marks_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='question_display_order_non_negative'),
        ),
        migrations.AddIndex(
            model_name='candidateassessment',
            index=models.Index(fields=['status'], name='assessments_status_5f7e17_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateassessment',
            index=models.Index(fields=['assessment_deadline'], name='assessments_assessm_c5da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateassessment',
            index=models.Index(fields=['application'], name='assessments_applica_86a272_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateassessment',
            constraint=models.UniqueConstraint(fields=('application', 'template', 'attempt_number'), name='unique_application_template_attempt'),
        ),
        migrations.AddConstraint(
            model_name='candidateassessment',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='assessment_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.UniqueConstraint(fields=('candidate_assessment', 'attempt_number'), name='unique_submission_attempt'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='submission_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='submission_file_size_non_negative'),
        ),
    ]
