# Generated by Django 6.0.6 on 2026-06-22 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_attempt', models.PositiveIntegerField()),
                ('provider', models.CharField(default='brevo', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('deferred', 'Deferred'), ('soft_bounced', 'Soft Bounced'), ('hard_bounced', 'Hard Bounced'), ('blocked', 'Blocked'), ('complaint', 'Complaint'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('recipient_email_snapshot', models.EmailField(max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('safe_failure_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='assessments.candidateassessment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_message_id'], name='idx_provider_msg_id')],
                'constraints': [models.UniqueConstraint(fields=('candidate_assessment', 'send_attempt'), name='unique_delivery_attempt'), models.CheckConstraint(condition=models.Q(('send_attempt__gt', 0)), name='delivery_attempt_positive')],
            },
        ),
    ]
