# Generated by Django 6.0.6 on 2026-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentemaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentemaildelivery',
            name='secure_token_digest',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('submitted', 'Submitted'), ('queued', 'Queued'), ('evaluating', 'Evaluating'), ('graded', 'Graded'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
