# Generated by Django 6.0.6 on 2026-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentemaildelivery_secure_token_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestionresult',
            name='execution_status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], default='skipped', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentquestionresult',
            name='safe_stdout_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='docker_image_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='execution_wall_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateassessment',
            name='evaluation_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateassessment',
            name='private_grading_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
