# Generated by Django 6.0.6 on 2026-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessmentquestionresult_execution_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassessment',
            name='dev_raw_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
