# Generated by Django 6.0.6 on 2026-06-23 09:32

import assessments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_candidateassessment_dev_raw_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='assessmentsubmission',
            name='submission_file_size_non_negative',
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='private_notebook',
            field=models.FileField(blank=True, null=True, storage=assessments.models.PrivateAssessmentFileSystemStorage(), upload_to='private_submissions/', validators=[assessments.models.validate_notebook_file]),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='sha256_digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__gte', 0), _connector='OR'), name='submission_file_size_non_negative'),
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='candidate_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.candidateassessment'),
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessmentquestion'),
        ),
        migrations.AddConstraint(
            model_name='candidateanswer',
            constraint=models.UniqueConstraint(fields=('candidate_assessment', 'question'), name='unique_candidate_assessment_question_answer'),
        ),
    ]
