# Generated by Django 6.0.6 on 2026-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_candidateanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='execution_mode',
            field=models.CharField(choices=[('function', 'Function Call'), ('stdio', 'Standard Input/Output')], default='function', max_length=30),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='function_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='hidden_test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='starter_code_per_language',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='visible_test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='selected_language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='hidden_tests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
