from django.urls import path
from .views import (
    AssessmentTemplateListCreateView,
    AssessmentTemplateDetailView,
    AssessmentQuestionCreateView,
    AssessmentQuestionDetailView,
    AssessmentQuestionReorderView,
    AssessmentTemplateActivateView,
    AssessmentTemplateArchiveView,
    AssessmentTemplateCloneView,
    AssessmentTemplatePreviewView,
    CandidateAssessmentListView,
    CandidateAssessmentSendView,
    CandidateAssessmentDetailView,
    CandidateAssessmentResendView,
    BrevoWebhookView,
    CandidateAccessView,
    CandidateNotebookDownloadView,
    CandidateNotebookUploadView,
    CandidateSaveAnswersView,
    CandidateRunCodeView,
    CandidateRunTestsView,
    CandidateAssessmentSubmitView,
    QueueSubmissionForEvaluationView,
    CandidateAssessmentRetryView,
    CandidateAssessmentResultView,
    CandidateAssessmentDevAccessLinkView,
    CandidateSubmittedAnswersView,
)

urlpatterns = [
    path(
        "templates/",
        AssessmentTemplateListCreateView.as_view(),
        name="assessment-template-list-create",
    ),
    path(
        "templates/<uuid:pk>/",
        AssessmentTemplateDetailView.as_view(),
        name="assessment-template-detail",
    ),
    path(
        "templates/<uuid:pk>/questions/",
        AssessmentQuestionCreateView.as_view(),
        name="assessment-question-create",
    ),
    path(
        "templates/<uuid:pk>/questions/<uuid:question_id>/",
        AssessmentQuestionDetailView.as_view(),
        name="assessment-question-detail",
    ),
    path(
        "templates/<uuid:pk>/questions/reorder/",
        AssessmentQuestionReorderView.as_view(),
        name="assessment-questions-reorder",
    ),
    path(
        "templates/<uuid:pk>/activate/",
        AssessmentTemplateActivateView.as_view(),
        name="assessment-template-activate",
    ),
    path(
        "templates/<uuid:pk>/archive/",
        AssessmentTemplateArchiveView.as_view(),
        name="assessment-template-archive",
    ),
    path(
        "templates/<uuid:pk>/clone/",
        AssessmentTemplateCloneView.as_view(),
        name="assessment-template-clone",
    ),
    path(
        "templates/<uuid:pk>/preview/",
        AssessmentTemplatePreviewView.as_view(),
        name="assessment-template-preview",
    ),
    path(
        "assignments/send/",
        CandidateAssessmentSendView.as_view(),
        name="assessment-send",
    ),
    path(
        "applications/<int:application_id>/assignments/",
        CandidateAssessmentListView.as_view(),
        name="assessment-list",
    ),
    path(
        "assignments/<uuid:pk>/",
        CandidateAssessmentDetailView.as_view(),
        name="assessment-detail",
    ),
    path(
        "assignments/<uuid:pk>/resend/",
        CandidateAssessmentResendView.as_view(),
        name="assessment-resend",
    ),
    path(
        "webhooks/brevo/",
        BrevoWebhookView.as_view(),
        name="brevo-webhook",
    ),
    path(
        "access/<str:token>/",
        CandidateAccessView.as_view(),
        name="candidate-assessment-access",
    ),
    path(
        "access/<str:token>/notebook/",
        CandidateNotebookDownloadView.as_view(),
        name="candidate-assessment-notebook",
    ),
    path(
        "access/<str:token>/upload/",
        CandidateNotebookUploadView.as_view(),
        name="candidate-assessment-upload",
    ),
    path(
        "access/<str:token>/save-answers/",
        CandidateSaveAnswersView.as_view(),
        name="candidate-assessment-save-answers",
    ),
    path(
        "access/<str:token>/run-code/",
        CandidateRunCodeView.as_view(),
        name="candidate-assessment-run-code",
    ),
    path(
        "access/<str:token>/run-tests/",
        CandidateRunTestsView.as_view(),
        name="candidate-assessment-run-tests",
    ),
    path(
        "access/<str:token>/submit/",
        CandidateAssessmentSubmitView.as_view(),
        name="candidate-assessment-submit",
    ),
    path(
        "assignments/<uuid:pk>/queue/",
        QueueSubmissionForEvaluationView.as_view(),
        name="assessment-queue",
    ),
    path(
        "assignments/<uuid:pk>/retry/",
        CandidateAssessmentRetryView.as_view(),
        name="assessment-retry",
    ),
    path(
        "assignments/<uuid:pk>/result/",
        CandidateAssessmentResultView.as_view(),
        name="assessment-result",
    ),
    path(
        "assignments/<uuid:pk>/dev-access-link/",
        CandidateAssessmentDevAccessLinkView.as_view(),
        name="assessment-dev-access-link",
    ),
    path(
        "assignments/<uuid:pk>/submitted-answers/",
        CandidateSubmittedAnswersView.as_view(),
        name="assessment-submitted-answers",
    ),
]
