# Generated by Django 6.0.6 on 2026-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='total_experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='worked_companies',
            field=models.TextField(blank=True),
        ),
    ]
