# Generated by Django 6.0.6 on 2026-06-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprogression',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprogression',
            name='updater_role',
            field=models.CharField(choices=[('hr', 'HR'), ('admin', 'Admin')], default='hr', max_length=20),
        ),
    ]
