# Generated by Django 6.0.6 on 2026-06-21 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('identity_type', models.CharField(choices=[('registered', 'Registered'), ('public', 'Public'), ('anonymous', 'Anonymous')], db_index=True, max_length=20)),
                ('normalized_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('public_email_key', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.candidateidentity'),
        ),
        migrations.AddConstraint(
            model_name='candidateidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_type', 'registered'), _negated=True), models.Q(('candidate_user__isnull', False), ('public_email_key__isnull', True)), _connector='OR'), name='registered_identity_integrity'),
        ),
        migrations.AddConstraint(
            model_name='candidateidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_type', 'public'), _negated=True), models.Q(('candidate_user__isnull', True), ('normalized_email__isnull', False), ('public_email_key__isnull', False)), _connector='OR'), name='public_identity_integrity'),
        ),
        migrations.AddConstraint(
            model_name='candidateidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_type', 'anonymous'), _negated=True), models.Q(('candidate_user__isnull', True), ('normalized_email__isnull', True), ('public_email_key__isnull', True)), _connector='OR'), name='anonymous_identity_integrity'),
        ),
    ]
