# Generated by Django 6.0.6 on 2026-06-21 17:16

from django.db import migrations


def backfill_candidate_identities(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    CandidateIdentity = apps.get_model('applications', 'CandidateIdentity')
    User = apps.get_model('auth', 'User')

    # Pre-cache user emails to avoid N+1 queries during iteration
    user_emails = {u.id: (u.email.strip().lower() if u.email else None) for u in User.objects.all()}

    queryset = Application.objects.order_by('pk')
    
    # Process applications in batches of 1000
    for app in queryset.iterator(chunk_size=1000):
        if app.candidate_id:
            # Registered application: identity by candidate_user (User ID)
            identity, created = CandidateIdentity.objects.get_or_create(
                candidate_user_id=app.candidate_id,
                defaults={
                    "identity_type": "registered",
                    "normalized_email": user_emails.get(app.candidate_id)
                }
            )
            app.candidate_identity = identity
            app.save(update_fields=['candidate_identity'])
        else:
            email = app.candidate_email.strip().lower() if app.candidate_email else ""
            if email:
                # Public valid email -> public identity by public_email_key
                identity, created = CandidateIdentity.objects.get_or_create(
                    public_email_key=email,
                    defaults={
                        "identity_type": "public",
                        "normalized_email": email
                    }
                )
                app.candidate_identity = identity
                app.save(update_fields=['candidate_identity'])
            else:
                # Blank/invalid email -> new anonymous identity
                identity = CandidateIdentity.objects.create(
                    identity_type="anonymous"
                )
                app.candidate_identity = identity
                app.save(update_fields=['candidate_identity'])


def reverse_backfill(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    Application.objects.all().update(candidate_identity=None)
    
    CandidateIdentity = apps.get_model('applications', 'CandidateIdentity')
    CandidateIdentity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_candidateidentity_application_candidate_identity_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_candidate_identities, reverse_code=reverse_backfill),
    ]
