# Generated by Django 6.0.6 on 2026-06-15 15:22

import uuid
from django.db import migrations, models


def generate_tokens(apps, schema_editor):
    """Generate unique tokens for existing jobs"""
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        if not job.application_token:
            job.application_token = uuid.uuid4()
            job.save(update_fields=['application_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='application_form_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='application_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_tokens),
        migrations.AlterField(
            model_name='job',
            name='application_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
