from django.urls import path
from .views import (
    ApplyJobView,
    MyApplicationsView,
    HRApplicationsView,
    UpdateApplicationStatusView,
    ReevaluateApplicationAIView,
    PublicApplicationCreateView,
    ApplicationInterviewsView,
    InterviewDetailView,
)
from .admin_views import (
    AdminHRListView,
    AdminHiredCandidatesListView,
    AdminCandidateProgressionCreateView,
    AdminCandidateProgressionDetailView,
    AdminToggleHRActiveView,
    AdminSystemActivityListView,
    AdminInterviewsListView,
    AdminResetHRPasswordView,
    AdminApplicationDirectoryView,
    AdminCandidateDirectoryView,
    AdminCandidateSummaryDetailView,
    AdminCandidateApplicationsListView,
    AdminCandidateActivityListView,
    AdminApplicationDetailView,
    AdminApplicationInterviewsListView,
    AdminApplicationProgressionsListView,
    AdminApplicationResumeView,
)


urlpatterns = [
    path("apply/", ApplyJobView.as_view(), name="apply_job"),
    path("my/", MyApplicationsView.as_view(), name="my_applications"),
    path("hr/", HRApplicationsView.as_view(), name="hr_applications"),
    path("<int:pk>/status/", UpdateApplicationStatusView.as_view(), name="update_application_status"),
    path("<int:pk>/reevaluate-ai/", ReevaluateApplicationAIView.as_view(), name="reevaluate_application_ai"),
    path("public/<uuid:token>/", PublicApplicationCreateView.as_view(), name="public_application_create"),
    path("<int:application_id>/interviews/", ApplicationInterviewsView.as_view(), name="application_interviews"),
    path("interviews/<int:pk>/", InterviewDetailView.as_view(), name="interview_detail"),
    path("admin/hrs/", AdminHRListView.as_view(), name="admin_hr_list"),
    path("admin/hrs/<int:pk>/toggle/", AdminToggleHRActiveView.as_view(), name="admin_hr_toggle_active"),
    path("admin/activity-log/", AdminSystemActivityListView.as_view(), name="admin_activity_log"),
    path("admin/hired-candidates/", AdminHiredCandidatesListView.as_view(), name="admin_hired_candidates_list"),
    path("admin/interviews/", AdminInterviewsListView.as_view(), name="admin_interviews_list"),
    path("admin/<int:pk>/progression/", AdminCandidateProgressionCreateView.as_view(), name="admin_candidate_progression_create"),
    path("admin/progression/<int:pk>/", AdminCandidateProgressionDetailView.as_view(), name="admin_candidate_progression_detail"),
    path("admin/hrs/<int:pk>/reset-password/", AdminResetHRPasswordView.as_view(), name="admin_hr_reset_password"),
    path("admin/directory/", AdminApplicationDirectoryView.as_view(), name="admin_application_directory"),
    path("admin/directory/<int:pk>/", AdminApplicationDetailView.as_view(), name="admin_application_detail_workspace"),
    path("admin/directory/<int:pk>/interviews/", AdminApplicationInterviewsListView.as_view(), name="admin_application_interviews_list"),
    path("admin/directory/<int:pk>/progressions/", AdminApplicationProgressionsListView.as_view(), name="admin_application_progressions_list"),
    path("admin/directory/<int:pk>/resume/", AdminApplicationResumeView.as_view(), name="admin_application_resume_stream"),
    
    path("admin/candidates/", AdminCandidateDirectoryView.as_view(), name="admin_candidate_directory"),
    path("admin/candidates/<uuid:candidate_uuid>/", AdminCandidateSummaryDetailView.as_view(), name="admin_candidate_summary_detail"),
    path("admin/candidates/<uuid:candidate_uuid>/applications/", AdminCandidateApplicationsListView.as_view(), name="admin_candidate_applications_list"),
    path("admin/candidates/<uuid:candidate_uuid>/activity/", AdminCandidateActivityListView.as_view(), name="admin_candidate_activity_list"),
]
